
%import the csv file manually as CELL, name has to be "untitled"!!!

addpath(genpath('DeepLearnToolbox'));
	addpath(genpath('Whetlab-Matlab-Client'));

	%parameters = {struct('name', 'LR', 'type', 'float', 'min', 1e-6, 'max', 2.0, 'size', 1),...
	%	      struct('name', 'drop', 'type', 'float', 'min', 0.0, 'max', 0.9, 'size', 1),...
        %      struct('name', 'epochs', 'type', 'int', 'min', 10, 'max', 200, 'size', 1),...
	%	      struct('name', 'activation', 'type', 'enum', 'options', {{'tanh_opt' 'sigm' 'relu'}}, 'size', 1),...
	%	      struct('name', 'hidden', 'type', 'int', 'min', 32, 'max', 2048, 'size', 1),...
	%	      struct('name', 'momentum', 'type', 'float', 'min', 0.0, 'max', 0.99, 'size', 1),...
	%	      struct('name', 'LR_decrease', 'type', 'float', 'min', 0.75, 'max', 1.0, 'size', 1),...
	%	      struct('name', 'regularization', 'type', 'float', 'min', 1e-6, 'max', 0.5, 'size', 1)};
		  
	%outcome.name = 'Accuracy';

	parameters = {struct('name', 'LR', 'type', 'float', 'min', -6, 'max', -1, 'size', 1),...
		      struct('name', 'drop', 'type', 'float', 'min', 0.0, 'max', 0.9, 'size', 1),...
              	      struct('name', 'epochs', 'type', 'enum', 'options', {{'epoch20' 'epoch40' 'epoch80'}}, 'size', 1),...
		      struct('name', 'activation', 'type', 'enum', 'options', {{'tanh_opt' 'sigm' 'relu'}}, 'size', 1),...
		      struct('name', 'hidden', 'type', 'enum', 'options', {{'size64' 'size128' 'size256' 'size512' 'size1024' 'size2048'}}, 'size', 1),...
		      struct('name', 'momentum', 'type', 'float', 'min', 0.0, 'max', 0.99, 'size', 1),...
		      struct('name', 'LR_decrease', 'type', 'float', 'min', 0.75, 'max', 1.0, 'size', 1),...
		      struct('name', 'regularization', 'type', 'float', 'min', 1e-6, 'max', 0.5, 'size', 1)};
		  
	outcome.name = 'negDistance';

		  
	scientist = whetlab('Whetlab_regression',...
		            'Try to find the rat!',...
		            parameters,...
		            outcome, true, '871cee3e-c6b4-460c-bd30-3ce9a48838ce');


nr_of_jobs=size(untitled,1)
for i=1:nr_of_jobs
job.LR=untitled{i,3};
job.LR_decrease=untitled{i,4};
accuracy=untitled{i,2};
job.activation=untitled{i,5};
job.drop=untitled{i,6};
job.epochs=untitled{i,7};
job.hidden=untitled{i,8};
job.momentum=untitled{i,9};
job.regularization=untitled{i,10};
scientist.update(job, accuracy)
end
